/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Grupo: typeof import('./src/components/Grupo.vue')['default']
    Informacao: typeof import('./src/components/Informacao.vue')['default']
    Parametro: typeof import('./src/components/Parametro.vue')['default']
    TrendCard: typeof import('./src/components/TrendCard.vue')['default']
  }
}
